version: '3.8'

services:

  mongodb:
    image: mongo
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    volumes:
      - ./mongo-data:/data/db
    networks:
      - flask-hadoop-app-network